name: 'Create shell script'
description: 'Creates a shell script from given content'

inputs:
  name:
    type: string
    required: true
    description: Path and name of shell file (may omit .sh extension if you like)
  content:
    type: string
    required: true
    description: Content of shell file
    
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        echo '#!/bin/bash' > "${{ inputs.name }}"
        echo '${{ inputs.content }}' >> "${{ inputs.name }}"
        chmod +x "${{ inputs.name }}"
